name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/cornerbrookweather:$(date +%s) .
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          # Retrieve the image name from the environment file
          # IMAGE_NAME=$(cat $GITHUB_ENV | grep IMAGE_NAME | cut -d'=' -f2)
          # docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          docker push ghcr.io/${{ github.repository_owner }}/cornerbrookweather:$(date +%s)
